Story 3 main story 3
Joshsilas/CoshAndJosminShop pull request #9
Opened 2024-01-18 17:57 UTC by Joshsilas

Search bar works perfectly, can now search in real time and click on the prodcut and it will take you to the product page and clear the search bar. Category menu now looks good, once again takes you to the correct category and clears the search bar so you dont get stuck. When products run out you are told and given a link back to home page. Which also clears the search bar.

2024-01-23 16:51 UTC, CosminDarius1 requested changes

2024-01-23 16:51 UTC, CosminDarius1 commented on src/Components/Category Menu/index.jsx
I would like to see the pop-up menu appearing below and not affecting anything :D Kinda hurts the eye when I see it appearing on the left side

2024-01-23 16:51 UTC, CosminDarius1 commented on src/Components/HomePage/index.jsx
>      const url = 'https://fakestoreapi.com/products';
Space between the imports and the rest of the code please

2024-01-24 11:25 UTC, Joshsilas commented on src/Components/Category Menu/index.jsx
The fix was so easy, Im super annoyed it took so long to work it out.

2024-01-24 14:56 UTC, CosminDarius1 approved these changes

2024-01-24 14:58 UTC, merged